service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1


functions:
  list:
    handler: controllers/todoController.js
    events:
     - http:
          path: todos
          method: get
          cors: true
